import './globals.css'
import {AppProvider} from '../context/AppContext';


export const metadata = {
  title: 'Moto Repuestos DK',
  description: 'Generated by create next app and Javier Aleman',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <AppProvider>
         {children}
        </AppProvider>
        </body>
    </html>
  )
}
